<img src="https://www.unir.net/wp-content/uploads/2019/11/Unir_2021_logo.svg" width="240" height="240" align="right"/>

<span>
<h2>Deep Learning en el diagnóstico del Alzheimer</h1> 
<h3>Preprocesamiento Imágenes de Resonancia Magnética</h3> 
</span>

<b>Juan David Escobar Escobar.</b></br>
* Julio 2022.
* Grupo 14.

## Instalar librerías

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
!pip install tensorflow-directml

In [ ]:
!pip install torch==1.4.0

In [ ]:
!pip install numpy==1.18.1

In [ ]:
!pip install pandas==0.25.3

In [ ]:
!pip install nibabel

In [ ]:
!pip install tqdm==4.42.1

In [ ]:
!pip install matplotlib

In [ ]:
!pip install opencv-python

In [ ]:
!pip install pandasql

In [ ]:
!pip install ipython-sql

In [2]:
!pip install autopep8

Collecting autopep8
  Downloading autopep8-1.6.0-py2.py3-none-any.whl (45 kB)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pycodestyle>=2.8.0
  Downloading pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
Installing collected packages: toml, pycodestyle, autopep8
Successfully installed autopep8-1.6.0 pycodestyle-2.8.0 toml-0.10.2

WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\gputfm\lib\site-packages)

## Importar librerias

In [3]:
import tensorflow
from tensorflow import keras

import matplotlib.pyplot as plt
import nibabel as nib

import os
import cv2
import nibabel as nib
import numpy as np

import pandas as pd
import sqlite3
from sqlite3 import Error
from pandasql import sqldf

In [ ]:
tensorflow.VERSION

## Exploración de datos

In [ ]:
"""
1. Lectura de las imagenes en formato .Nifti

2. Imprime el atributo shape que nos dice que se trata de un escaneo 3D 
   (anatómico) # y tiene 256 vóxeles en la primera dimensión, 
   256 vóxeles en la segunda dimensión y 180 vóxeles en la 
   tercera dimensión.  
   
NOTAS: 
a. Las imagenes NIFTI contienen (El encabezado con metadatos,
Los datos de la imagen y La matriz afín). 

b. En el caso de los archivos fMRI, la cuarta dimensión (casi) siempre 
representa la dimensión "tiempo". Por lo tanto, puede suponer que 
una imagen nifti de un archivo fMRI tiene 4 dimensiones, siendo las
tres primeras las dimensiones espaciales 
(similar al archivo anatómico de MRI:) 
y el último (cuarto) siendo la dimensión del tiempo ().
"""

fig = plt.figure()
#path = r"C:\Users\Juan David\Documents\TFM\ADNI1_Complete 1Yr 1.5T (1)\ADNI\031_S_0568\MPR-R__GradWarp__N3__Scaled\2006-12-05_12_35_03.0\I65041\ADNI_031_S_0568_MR_MPR-R__GradWarp__N3__Scaled_Br_20070806132107428_S23625_I65041.nii"

epi_img  = nib.load(path)
epi_img_data  = epi_img.get_fdata()

print(type(epi_img_data))
print(type(epi_img_data.shape))

## Extraccion y carga

In [ ]:
"""Esta funcion guarda las imagenes provenientes del corte coaxial y axial de una imagen NIFTI, en
   una sub carpeta llamada jpg

Parameters
----------
list : numpy.ndarray
       datos numericos de una imagen en formato NIFTI (Slide 1 corte (Dimension 1: Axial))
       datos numericos de una imagen en formato NIFTI (Slide 1 corte (Dimension 2: Coronal))

Ej:
[{
    'list_volumen': [array([[0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.],
                           ...,
                           [0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.]]), array([[0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.],
                           ...,
                           [0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.],
                           [0., 0., 0., ..., 0., 0., 0.]])], 
      'save_path': 'D:\\ADNI - IDA\\ADNI1_Complete 1Yr 1.5T\\ADNI
                        \\023_S_0058\\MPR__GradWarp__B1_Correction__N3__Scaled
                        \\2005-11-30_09_36_10.0\\I108504\\jpg', 
      'list_file_names': ['DNI_023_S_0058_MR_MPR__GradWarp__B1_Correction__N3__
                          Scaled_Br_20080605143248460_S10335_I108504_coronal', 
                         'DNI_023_S_0058_MR_MPR__GradWarp__B1_Correction__N3__
                         Scaled_Br_20080605143248460_S10335_I108504_axial']
}] 

Returns: 
-------
msg: Exito o Error al guardar las imagenes en formato JPG
"""

def save_slice_volume_in_jpg(list_slices_save_jpg ):
   
    msg_result = 'Exito'    
    for item in list_slices_save_jpg:
        
        list_volume = item["list_volumen"]
        save_path  = item["save_path"]
        list_file_names = item["list_file_names"]
        
        #print(list_volume)
        #print(save_path)
        #print(list_file_names)
        
        for index, volume in enumerate(list_volume):
  
            shape = volume.shape             
            file_name = list_file_names[index]    
        
            #print(shape)
            #print(file_name)

            # traducir intensidad a 0-255 (escala de grises)
            v_max = np.max(volume)
            v_min = np.min(volume)
            volume_norm = (volume - v_min) / (v_max - v_min)
            volume_norm = (volume_norm * 255).astype("int")

            # crear ruta de alamacenamiento en caso de que no exista
            if not os.path.exists(save_path):
                os.makedirs(save_path)        
            try:
                
                # almacenar archivo jpg en la nueva ruta
                new_current_flie = file_name + ".jpg"
                abs_path = os.path.join(save_path, new_current_flie)
                cv2.imwrite(abs_path, volume_norm)
            except:
                msg_result = msg_result + 'Error guardando las imagen ' + new_current_flie + ','
                len_msg = len(msg_result)
                msg_result = msg_result[0: len_msg -1] # Eliminamos la ultima coma

        return msg_result

## Lectura y conversion archivos en formato NIFTI a JPG

In [ ]:
""" Registrar log de cada imagen jpg almacenadaI45108.nii   

Parameters
----------
df_pd_log          : pandas.dataframe
list_file_names    : list
current_folder_nii : str
current_file_nii   : str
file               : str
fil_jpg            : str
state              : str

Retorno
----------
df_pd_log          : pandas.dataframe
"""

def registra_log_jpg(df_pd_log, list_file_names, current_folder_nii, current_file_nii, file, save_path, state, msg, current_date):
    
    list_current_folder_nii = current_folder_nii.split("\\")                   
    image_data_id = list_current_folder_nii[7]
    subject = list_current_folder_nii[4]
    path_nii = current_file_nii
    file_name_nii = file
    path_jpg = save_path
    
    for fil_jpg in list_file_names:            
        
        file_name_jpg = fil_jpg # "_coronal", "_axial"               
 
        current_row = {\
                         'image_data_id': image_data_id,\
                         'subject': subject,\
                         'path_nii': path_nii,\
                         'file_name_nii': file_name_nii,\
                         'path_jpg': path_jpg,\
                         'file_name_jpg': file_name_jpg,\
                         'state': state,\
                         'msg': msg,\
                         'creation_date': current_date\
                       }\
    
        df_pd_log = df_pd_log.append(current_row, ignore_index = True)      
        
    return df_pd_log

In [ ]:
"""
1. Extraccion de imagenes NIFTI (.nii) de estructura jerarquica de carpetas donde se almacenan, como 
   la del ejemplo a continuacion:
   
   a. Raiz => D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI
      b. Sub folder 1 => 002_S_0295 
         c. Sub folder 2 => MPR__GradWarp__B1_Correction__N3__Scaled 
            d. Sub folder 3 => 2006-04-18_08_20_30.0 
               e. Sub folder => I45108 
                    File => ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070319113623975_S13408_I45108.nii
                  
2. Lectura de las imagenes en formato Nifti, en 3D donde cada dimension contiene una secuencia de 
   imagenes para los cortes de las Imagenes de resonancia magnetica cerebral (Dimension 1: Axial, Dimension 2: Coronal
   y Dimesion 3:Sagital).
   
3. Crear Sub folder en el nivel "g" al interior del nivel "e" llamado "jpg" en el cual se almacenaran los cortes 
   Axial y Coronal del cerebro, ya que son las imagenes que proveen mas informacion para la deteccion del Alzheimer,
  para ambos cortes se seleccionara la imagen que se ubica en el centro de cada dimension de la imagend 3D en formato Nifti,
  ya que son las que permiten ver cada corte de manera completa.
  
4. Registra una tabla de log con la informacion de las imagenes almacenadas. 
"""
import os
import pandas as pd
import pytz
from datetime import datetime

# Dataframe para registro de log de auditoria
df_pd_log = pd.DataFrame()
df_pd_log = pd.DataFrame(columns=['image_data_id',\
                                  'subject',\
                                  'path_nii',\
                                  'file_name_nii',\
                                  'path_jpg',\
                                  'file_name_jpg',\
                                  'state',\
                                  'msg',\
                                  'creation_date'\
                                 ])

# Variables de directorios
path_root = r'D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI'
sub_folder_new_format = "\jpg"
count_dirs = 0

# Variables de tiempo
zone = pytz.timezone('America/Bogota')
date = datetime.now(zone)
current_date = date.strftime("%d/%m/%Y %H:%M:%S")
current_date = datetime.strptime(current_date, "%d/%m/%Y %H:%M:%S")
current_date_log_file = str(date.day).zfill(2) + str(date.month).zfill(2) + str(date.year) + "_" + str(date.hour) + "_" + str(date.minute)+ "_" + str(date.second)

for root, dirs, files in os.walk(path_root):   
    
    dirs.sort() # ordenar subdirectorios asendente      
    
    for file in files:
        
        if file.endswith(".nii"):
            
            count_dirs = count_dirs + 1
#             if count_dirs > 3:
#                 break
            
            list_volumen    = []
            save_path  = ''
            list_file_names = []
                               
            current_file_nii = os.path.join(root, file)  # D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\023_S_0058\MPR-R__GradWarp__B1_Correction__N3__Scaled\2006-06-22_16_13_35.0\I31008\ADNI_023_S_0058_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061130142201343_S15796_I31008.nii     
            current_folder_nii = os.path.join(root)      # D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\023_S_0058\MPR-R__GradWarp__B1_Correction__N3__Scaled\2006-06-22_16_13_35.0\I31008               
            current_folder_new_jpg = current_folder_nii + sub_folder_new_format                                
            current_file = file[0: len(file) - 4]
                                
            # 1. Leer imagen iterada
            mri  = nib.load(current_file_nii)
            mri_data = mri.get_fdata()
            shape = mri_data.shape            
            
            # 2. Obtener los valores de las 3D del la imagen .nii
            n_i, n_j, n_k = mri_data.shape

            # 3. Obtener el ejecentral de cada dimension
            center_i = (n_i - 1) // 2  # // division entera
            center_j = (n_j - 1) // 2
            center_k = (n_k - 1) // 2

            # 4. Obtener cortes de cada dimension ubicados en el centro de cada dimension
            slice_coronal_0 = mri_data[center_i, :, :] # Coronal
            slice_axial_1 = mri_data[:, center_j, :] # Axial
            slice_sagital_2 = mri_data[:, :, center_k] # Sagital
            
            # 5. Almacenar volumenes a guardar en formato jpg           
            list_volumen.append(slice_coronal_0)
            list_volumen.append(slice_axial_1)
                                 
            # 6. Almacenar ruta donde se va almacenar la imagen jpg
            save_path = current_folder_new_jpg
            
            # 7. Almacenar nombre del archivo = nombre original + _coronal o _axial
            current_file_coronal = current_file + "_coronal"
            current_file_axial = current_file + "_axial"                  
            list_file_names.append(current_file_coronal)
            list_file_names.append(current_file_axial) 
                 
            # 8. Almacenar en objeto tipo diccionario 
            list_slices_save_jpg = []
            current_dic = {}
            
            current_dic["list_volumen"] = list_volumen
            current_dic["save_path"] = save_path
            current_dic["list_file_names"] = list_file_names
                                      
            list_slices_save_jpg.append(current_dic)            
            # print(list_slices_save_jpg, "\n")
            
            # 9. Almacenar cortes en formato .jpg en sub folder contenedor de la imagen .nii
            msg_result = save_slice_volume_in_jpg(list_slices_save_jpg)
                                        
            # 10. Actualizar estado
            if msg_result == "Exito":
                # print(msg_result, "\n",  list_file_names)
                state = "Exito"               
            else:
                state = "Error"              
                # print(msg_result)
                
            # 11. Registrar log de auditoria de las imagenes almacenas en jpg   
            df_pd_log = registra_log_jpg(df_pd_log,
                                         list_file_names,
                                         current_folder_nii,
                                         current_file_nii,
                                         file,
                                         save_path,                            
                                         state,
                                         msg_result,
                                         current_date
                                        )    
     
print("Fin del ciclo de almacenamiento")
# return df_pd_log
path_log_root = r"D:\ADNI - IDA\A_Metadatos\log"
file_name_ext_load = r"\dl_alzheimer_log_extraction_nii_to_jpg_" + current_date_log_file + ".csv"
path_log_ext_load = path_log_root + file_name_ext_load
print(path_log_ext_load)

df_pd_log.to_csv (path_log_ext_load, index = None, header=True)
display(df_pd_log)

## Crear tabla de metadatos

In [8]:
def crear_tbl_metadatos_consolidado():
    file_demografico_metadatos = r"D:\ADNI - IDA\A_Metadatos\ADNI1_Complete_1Yr_1.5T_4_27_2022.csv"
    df_demografico_metadatos = pd.read_csv(file_demografico_metadatos)
    df_demografico_metadatos.columns= df_demografico_metadatos.columns.str.lower()
    df_demografico_metadatos =  df_demografico_metadatos.rename(columns={"image data id": "image_data_id_m", "acq date_m": "acq_date", "subject": "subject_m", "group": "group_m"})


    file_name_ext_load = r"D:\ADNI - IDA\A_Metadatos\log\dl_alzheimer_log_extraction_nii_to_jpg_05052022_12_32_2.csv"
    df_log = pd.read_csv(file_name_ext_load)        

    df_metadatos_con = df_log.merge(df_demografico_metadatos,  how='inner',
                                    left_on=['image_data_id','subject'],
                                    right_on = ['image_data_id_m','subject_m'])

    df_metadatos_con['orden'] = np.arange(0, len(df_metadatos_con))

    df_metadatos_con.drop(['image_data_id_m', 'subject_m'], axis = 1, inplace = True) 

    return df_metadatos_con

In [9]:
df_metadatos_con = crear_tbl_metadatos_consolidado()
df_metadatos_con.shape
df_metadatos_con.columns

Index(['image_data_id', 'subject', 'path_nii', 'file_name_nii', 'path_jpg',
       'file_name_jpg', 'state', 'msg', 'creation_date', 'group_m', 'sex',
       'age', 'visit', 'modality', 'description', 'type', 'acq date', 'format',
       'downloaded', 'orden'],
      dtype='object')

In [10]:
df_metadatos_con.tail(3)

,image_data_id,subject,path_nii,file_name_nii,path_jpg,file_name_jpg,state,msg,creation_date,group_m,sex,age,visit,modality,description,type,acq date,format,downloaded,orden
4585,I97327,941_S_1311,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\941...,ADNI_941_S_1311_MR_MPR__GradWarp__B1_Correctio...,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\941...,ADNI_941_S_1311_MR_MPR__GradWarp__B1_Correctio...,Exito,Exito,2022-05-05 12:32:02,MCI,M,69,1,MRI,MPR; GradWarp; B1 Correction; N3; Scaled,Processed,3/02/2007,NiFTI,NaN,4585
4586,I112538,941_S_1311,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\941...,ADNI_941_S_1311_MR_MPR__GradWarp__B1_Correctio...,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\941...,ADNI_941_S_1311_MR_MPR__GradWarp__B1_Correctio...,Exito,Exito,2022-05-05 12:32:02,MCI,M,70,4,MRI,MPR; GradWarp; B1 Correction; N3; Scaled,Processed,6/01/2008,NiFTI,NaN,4586
4587,I112538,941_S_1311,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\941...,ADNI_941_S_1311_MR_MPR__GradWarp__B1_Correctio...,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\941...,ADNI_941_S_1311_MR_MPR__GradWarp__B1_Correctio...,Exito,Exito,2022-05-05 12:32:02,MCI,M,70,4,MRI,MPR; GradWarp; B1 Correction; N3; Scaled,Processed,6/01/2008,NiFTI,NaN,4587

In [14]:
df_metadatos_con.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4588 entries, 0 to 4587
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   image_data_id  4588 non-null   object
 1   subject        4588 non-null   object
 2   path_nii       4588 non-null   object
 3   file_name_nii  4588 non-null   object
 4   path_jpg       4588 non-null   object
 5   file_name_jpg  4588 non-null   object
 6   state          4588 non-null   object
 7   msg            4588 non-null   object
 8   creation_date  4588 non-null   object
 9   group_m        4588 non-null   object
 10  sex            4588 non-null   object
 11  age            4588 non-null   int64
 12  visit          4588 non-null   int64
 13  modality       4588 non-null   object
 14  description    4588 non-null   object
 15  type           4588 non-null   object
 16  acq date       4588 non-null   object
 17  format         4588 non-null   object
 18  downloaded     8 non-null      object
dtypes: int64(2), object(17)
memory usage: 716.9+ KB

## Registrar tabla de log en BD

In [11]:
%run ./Helpers/sqllite_helper.ipynb
helper_sqllite()

helper sqllite loaded..

In [15]:
"""Registrar log de carga"""

database = r"C:\sqllite\alzheimer_db.db"
conn = create_connection(database)

drop_table(conn, "DROP TABLE log_metadatos_consolidado")
df_metadatos_con.to_sql("log_metadatos_consolidado", con = conn)

<sqlite3.Connection object at 0x000002234F68CE30>
no such table: log_metadatos_consolidado

In [16]:
query = "SELECT * FROM log_metadatos_consolidado LIMIT 3"
df_rs_query = query_table(conn, query)
df_rs_query

,index,image_data_id,subject,path_nii,file_name_nii,path_jpg,file_name_jpg,state,msg,creation_date,...,sex,age,visit,modality,description,type,acq date,format,downloaded,orden
0,0,I45108,002_S_0295,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\002...,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correctio...,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\002...,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correctio...,Exito,Exito,2022-05-05 12:32:02,...,M,85,1,MRI,MPR; GradWarp; B1 Correction; N3; Scaled,Processed,4/18/2006,NiFTI,None,0
1,1,I45108,002_S_0295,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\002...,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correctio...,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\002...,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correctio...,Exito,Exito,2022-05-05 12:32:02,...,M,85,1,MRI,MPR; GradWarp; B1 Correction; N3; Scaled,Processed,4/18/2006,NiFTI,None,1
2,2,I40966,002_S_0295,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\002...,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correctio...,D:\ADNI - IDA\ADNI1_Complete 1Yr 1.5T\ADNI\002...,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correctio...,Exito,Exito,2022-05-05 12:32:02,...,M,85,3,MRI,MPR; GradWarp; B1 Correction; N3; Scaled,Processed,11/02/2006,NiFTI,None,2

## Exploracion de datos

In [55]:
"""Datos agrupados por rango de edades """

df_metadatos_con['rangos_edad'] = np.select(
[
    ((df_metadatos_con['age'] >= 55) & (df_metadatos_con['age'] < 67)),
    ((df_metadatos_con['age'] >= 67) & (df_metadatos_con['age'] < 79)),
    ((df_metadatos_con['age'] >= 79) & (df_metadatos_con['age'] <= 91))
    
], 
[
   "[55-67]",
   "[67-79]",
   "[79-91]"
], 
default='[]')

In [56]:

df_metadatos_con.rangos_edad.unique()

array(['[79-91]', '[67-79]', '[55-67]'], dtype=object)

In [57]:
"""Datos agrupados por rango de edades """

from pandasql import sqldf

query = "SELECT * FROM df_metadatos_con "

query = "SELECT rangos_edad as clasificacion,\
        count(*) AS cantidad \
        FROM df_metadatos_con \
        group by rangos_edad \
        order by rangos_edad "

df_metadatos_con_agg = sqldf(query)
df_metadatos_con_agg

  clasificacion  cantidad
0       [55-67]       464
1       [67-79]      2570
2       [79-91]      1554

In [58]:
"""Datos agrupados por evolucion de la enfermedad de Alzheimer """

from pandasql import sqldf

query = "SELECT * FROM df_metadatos_con "

query = "SELECT group_m as clasificacion,\
        count(*) AS cantidad \
        FROM df_metadatos_con \
        group by group_m \
        order by group_m "

df_metadatos_con_agg = sqldf(query)
df_metadatos_con_agg

  clasificacion  cantidad
0            AD       952
1            CN      1410
2           MCI      2226

In [59]:
"""Datos agrupados por evolucion de la enfermedad de Alzheimer y Sexo """

from pandasql import sqldf

query = "SELECT * FROM df_metadatos_con "

query = "SELECT group_m as clasificacion,\
                sex as sexo,\
        count(*) AS cantidad \
        FROM df_metadatos_con \
        group by group_m,sex \
        order by group_m "

df_metadatos_con_agg = sqldf(query)
df_metadatos_con_agg

  clasificacion sexo  cantidad
0            AD    F       442
1            AD    M       510
2            CN    F       670
3            CN    M       740
4           MCI    F       794
5           MCI    M      1432

In [ ]:
"""Datos agrupados por Sexo """

from pandasql import sqldf

query = "SELECT * FROM df_metadatos_con "

query = "SELECT sex as sexo,\
        count(*) AS cantidad \
        FROM df_metadatos_con \
        group by sex \
        order by sex "

df_metadatos_con_agg = sqldf(query)
df_metadatos_con_agg

### Fuentes de datos de acceso abierto

A continuación otra pequeña muestra de fuentes de datos de acceso abierto: 
      
+ [Kaggle](https://www.kaggle.com/datasets). Se creó para ayudar a las empresas a organizar concursos de ciencia de datos para resolver problemas complejos utilizando datos. 
+ [FiveThirtyEight](https://data.fivethirtyeight.com/). Datos de periodismo. Datos detras de las noticias de política, ciencia, cultura, deportes, entre otros. Principalmente contiene información de Estados Unidos.

# References

<a name="cite-PER-GRA:2007"/><sup>[^](#ref-2) </sup>P&eacute;rez, Fernando and Granger, Brian E.. 2007. _IPython: a System for Interactive Scientific Computing_. [URL](http://ipython.org)

<a name="cite-calicoww2:2"/><sup>[^](#ref-3) </sup>Kepps, Milo . 2002. _Rebuilding Calico After Japanese Occupation_.

Alzheimer clasification: https://levelup.gitconnected.com/deep-learning-for-alzheimers-classification-57611161e442

Trabajando con datos de MRI en Python: https://lukas-snoek.com/NI-edu/fMRI-introduction/week_1/python_for_mri.html


http://openaccess.uoc.edu/webapps/o2/bitstream/10609/81588/6/seganamiTFM0618memoria.pdf

https://nipy.org/nibabel/tutorials.html#tutorials

https://facundoq.github.io/courses/aa2018/res/04_imagenes_numpy.html

https://carpentries-incubator.github.io/SDC-BIDS-IntroMRI/anatomy-of-nifti/index.html

https://dartbrains.org/content/GLM_Single_Subject_Model.html

https://peerherholz.github.io/workshop_weizmann/data/image_manipulation_nibabel.html

https://lukas-snoek.com/NI-edu/fMRI-introduction/week_1/python_for_mri.html